<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit5fd5564a422182a035ec0eac6ae23f26
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('Alma\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \Alma\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit5fd5564a422182a035ec0eac6ae23f26', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \Alma\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit5fd5564a422182a035ec0eac6ae23f26', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\Alma\Vendor\Composer\Autoload\ComposerStaticInit5fd5564a422182a035ec0eac6ae23f26::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        $filesToLoad = \Alma\Vendor\Composer\Autoload\ComposerStaticInit5fd5564a422182a035ec0eac6ae23f26::$files;
        $requireFile = \Closure::bind(static function ($fileIdentifier, $file) {
            if (empty($GLOBALS['__composer_autoload_files'][$fileIdentifier])) {
                $GLOBALS['__composer_autoload_files'][$fileIdentifier] = true;

                require $file;
            }
        }, null, null);
        foreach ($filesToLoad as $fileIdentifier => $file) {
            $requireFile($fileIdentifier, $file);
        }

        return $loader;
    }
}
