<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Alma\\Vendor\\Psr\\Log\\' => array($vendorDir . '/psr/log/Psr/Log'),
    'Alma\\Vendor\\Psr\\Http\\Message\\' => array($vendorDir . '/psr/http-factory/src', $vendorDir . '/psr/http-message/src'),
    'Alma\\Vendor\\Psr\\Http\\Client\\' => array($vendorDir . '/psr/http-client/src'),
    'Alma\\Vendor\\GuzzleHttp\\Psr7\\' => array($vendorDir . '/guzzlehttp/psr7/src'),
    'Alma\\Vendor\\GuzzleHttp\\Promise\\' => array($vendorDir . '/guzzlehttp/promises/src'),
    'Alma\\Vendor\\GuzzleHttp\\' => array($vendorDir . '/guzzlehttp/guzzle/src'),
    'Alma\\Vendor\\Dice\\' => array($vendorDir . '/level-2/dice'),
    'Alma\\Vendor\\Alma\\Plugin\\' => array($vendorDir . '/alma/alma-php-client/src/Plugin'),
    'Alma\\Vendor\\Alma\\Client\\' => array($vendorDir . '/alma/alma-php-client/src/Client'),
    'Alma\\Gateway\\' => array($baseDir . '/includes'),
);
