<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'e3811edf620df906119dde7e62fb7164' => $vendorDir . '/symfony/deprecation-contracts/function.php',
    'f1356847d256a93f7928631f13c85add' => $vendorDir . '/ralouphie/getallheaders/src/getallheaders.php',
    '1ca077f53716943ed824d66c26b73e2c' => $vendorDir . '/symfony/polyfill-php80/bootstrap.php',
    '6672bcf5979dfbf039eef83608d74702' => $vendorDir . '/guzzlehttp/guzzle/src/functions_include.php',
);
